name: Tag npm bumps and build release artifacts

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    uses: nbr23/github-workflows/.github/workflows/tag-npm-version-bump.yml@e1e97176734f2c8badaea5e1811231dcdd11a208
    with:
      create_release: true
      build_command: make all
      release_assets: |
        {
          "bunny-pack-{tag}-chrome.zip": "web-ext-artifacts/*.zip"
        }
