name: Tag npm bumps

on:
  push:
    branches:
      - master
jobs:
  call-workflow-passing-data:
    uses: nbr23/github-workflows/.github/workflows/tag-npm-version-bump.yml@75c68d04b6181384e97cb2f67c37c8cddeb6e099
    with:
        create_release: true
